import { NAME } from "./constants";

export const 
  FETCH_START    = `${NAME}/FETCH_START`,
  FETCH_SUCCESS  = `${NAME}/FETCH_SUCCESS`,
  FETCH_ERROR    = `${NAME}/FETCH_ERROR`,
  CREATE_SUCCESS = `${NAME}/CREATE_SUCCESS`,
  UPDATE_SUCCESS = `${NAME}/UPDATE_SUCCESS`,
  REMOVE_SUCCESS = `${NAME}/REMOVE_SUCCESS`